### ISSUE TITLE
Hide and Show a view when gesture ends

### ISSUE THREAD

**Issue by sakshigidwani93** [shubhankaryash/ScrollCoordinator#3]
In the function gestureDidFinish i want to access a view and hide and show it on basis scroll top or bottom.

**Comment by shubhankaryash** [comment]
@sakshigidwani93 You can create a new behaviour for this and add this functionality in the gestureDidFinish

**Comment by sakshigidwani93** [comment]
Thanks @shubhankaryash. I created a new behavior and trying to access the view by following code but it is not giving me the expected output.
```
let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let tempViewController = storyboard.instantiateViewController(withIdentifier: "AnchorBehaviourViewController") as! AnchorBehaviourViewController
        tempViewController.vwHeader.isHidden = false
```

**Comment by shubhankaryash** [comment]
@sakshigidwani93 Sorry I am not able to understand what the problem is. Is this fragment of code written within the behaviour? Could you please ellaborate?

**Comment by sakshigidwani93** [comment]
@shubhankaryash i have written this code inside gestureDidFinish. I want to hide and show "vwHeader" based on condition. The problem is the vwHeader is not getting hidden. And as you said i have written a custom behavior.

**Comment by sakshigidwani93** [comment]
Thanks @shubhankaryash the issue is solved . I used protocol and delegates and the issue got solved.

**Comment by shubhankaryash** [comment]
I am not sure what the issue was but it's great that it got resolved. 👍
